kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: longhorn-frontend
  namespace: longhorn-system

spec:
  entryPoints: 
    - websecure
  routes:
  - match: Host(`longhorn.turing.pi`) 
    kind: Rule
    services:
    - name: longhorn-frontend
      port: 80
