apiVersion: apps/v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: blue-app
  name: blue-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: blue-app
        type: canary
    spec:
      volumes:
      - name: host-volume
        persistentVolumeClaim:
          claimName: blue-app
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: volv
      - image: debian
        name: debian
        volumeMounts:
        - mountPath: /host-vol
          name: volv
        command: ["/bin/sh", "-c", "echo Welcome to BLUE App! > /host-vol/index.html ; sleep infinity"]
      volumes:
        - name: volv
          persistentVolumeClaim:
           claimName: blue-app
status: {}
